// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	KV_STORAGE: KVNamespace;
	DB: D1Database,
	API_URL: string,
	LOCAL_ACCEPTED_ORIGIN: string
}
